name: CI

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-combination: ["u32", "u64", "u32,ct-maybe", "u64,ct-maybe"]
        release: ["", "--release"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Check
      run: |
        cargo check ${{ matrix.release }} --features ${{ matrix.feature-combination }}

    - name: Test
      run: |
        cargo test ${{ matrix.release }} --features ${{ matrix.feature-combination }}

