name: Docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "--html-in-header /home/runner/work/rsa-cortex-m4/rsa-cortex-m4/src/docs-header.html"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7em-none-eabi
        profile: minimal

    - name: Build Documentation
      run: cargo doc && .github/workflows/make-toplevel-index.sh

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
